embed_assets: on
template_function: _.template

javascripts:
  workspace:
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.5.js
    - public/javascripts/vendor/*.js
    - public/javascripts/application.js
    - public/javascripts/views/**/*.js
    - app/views/backlogs/*.jst
    - app/views/companies/*.jst

stylesheets:
  common:
    - public/stylesheets/global.css