embed_assets: on
template_function: _.template
compressor_options:
  line_break: 0
  optimize: false
  munge: false

javascripts:
  workspace:
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.7.js
    - public/javascripts/vendor/*.js
    - public/javascripts/locale/*.js
    - public/javascripts/utilities.js
    - public/javascripts/application.js
    - public/javascripts/views/notice_view.js
    - app/views/**/*.jst
  backlog:
    - public/javascripts/models/**/*.js
    - public/javascripts/collections/**/*.js
    - public/javascripts/controllers/**/*.js
    - public/javascripts/views/helpers/*.js
    - public/javascripts/views/base/*.js
    - public/javascripts/views/acceptance_criteria_view.js
    - public/javascripts/views/backlogs_view.js
    - public/javascripts/views/backlog_data_area_view.js
    - public/javascripts/views/backlog_presence_view.js
    - public/javascripts/views/backlog_stats_view.js
    - public/javascripts/views/sprints_view.js
    - public/javascripts/views/sprint_tabs_view.js
    - public/javascripts/views/stories_view.js
    - public/javascripts/views/themes_view.js
    - public/javascripts/routers/backlog_router.js
  backlog_walkthrough:
    - public/javascripts/vendor/conditional/guiders-1.2.0.js
    - public/javascripts/sections/backlog_walkthrough.js
  ie_compatibility:
    - public/javascripts/ie_compatibility/*
  users:
    - public/javascripts/sections/users.js
  register:
    - public/javascripts/sections/shared_backlog_preferences.js
    - public/javascripts/sections/register_and_account.js
  backlog_settings:
    - public/javascripts/views/backlog_settings_view.js
    - public/javascripts/routers/backlog_settings_router.js
  manage_backlog:
    - public/javascripts/sections/shared_backlog_preferences.js
    - public/javascripts/sections/manage_backlog.js
  validation:
    - public/javascripts/vendor/conditional/jquery.validate.js
  snapshots:
    - public/javascripts/sections/snapshots.js
  beta_signup:
    - public/javascripts/vendor/conditional/jquery.lightbox-0.5.js
    - public/javascripts/sections/beta_signup.js
  charts:
    - public/javascripts/vendor/conditional/highcharts.src.js
  company:
    - public/javascripts/sections/shared_backlog_preferences.js
    - public/javascripts/sections/company.js
  account:
    - public/javascripts/sections/register_and_account.js
stylesheets:
  common:
    - tmp/stylesheets/global.css
    - public/stylesheets/ui-lightness/jquery-ui-1.8.9.custom.css
  backlog_walkthrough:
    - public/stylesheets/guiders-1.2.0.css
  ie_compatibility:
    - tmp/stylesheets/ie_compatibility.css
  snapshots:
    - tmp/stylesheets/snapshots.css
  snapshots_print:
    - tmp/stylesheets/snapshots_print.css
  beta_signup:
    - public/stylesheets/jquery.lightbox-0.5.css
    - tmp/stylesheets/beta_signup.css
  admin:
    - tmp/stylesheets/admin.css