embed_assets: on
template_function: _.template

javascripts:
  workspace:
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.5.js
    - public/javascripts/vendor/*.js
    - public/javascripts/utilities.js
    - public/javascripts/application.js
    - app/views/**/*.jst
    - public/javascripts/models/**/*.js
    - public/javascripts/collections/**/*.js
    - public/javascripts/controllers/**/*.js
    - public/javascripts/views/base/*.js
    - public/javascripts/views/*.js
  ie_compatibility:
    - public/javascripts/ie_compatibility/*
  users:
    - public/javascripts/sections/users.js
stylesheets:
  common:
    - public/stylesheets/global.css
    - public/stylesheets/ui-lightness/jquery-ui-1.8.9.custom.css
  ie_compatibility:
    - public/stylesheets/ie_compatibility.css