embed_assets: on
template_function: _.template

javascripts:
  workspace:
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/jquery-1.5.js
    - public/javascripts/vendor/*.js
    - public/javascripts/application.js
    - app/views/**/*.jst
    - public/javascripts/models/**/*.js
    - public/javascripts/collections/**/*.js
    - public/javascripts/controllers/**/*.js
    - public/javascripts/views/base/*.js
    - public/javascripts/views/*.js

stylesheets:
  common:
    - public/stylesheets/global.css